apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-auth
  labels:
    app: teastore
    run: teastore-auth
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: teastore
      run: teastore-auth
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-auth
    spec:
      terminationGracePeriodSeconds: 0
      initContainers:
        - name: wait-for-teastore-persistence
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "ðŸ•“ Waiting for teastore-persistence:8080..."
              until nc -z teastore-persistence 8080; do
                echo "teastore-persistence not ready yet... sleeping 5s"
                sleep 5
              done
              echo "âœ… teastore-persistence is ready!"
      containers:
        - name: teastore-auth
          image: "{{ .Values.image.auth }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: HOST_NAME
              value: "teastore-auth"
            - name: REGISTRY_HOST
              value: "teastore-registry"
            - name: RABBITMQ_HOST
              value: "teastore-rabbitmq"
          readinessProbe:
            httpGet:
              path: "/tools.descartes.teastore.auth/rest/ready/isready"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.auth.resources.requests.cpu }}
              memory: {{ .Values.auth.resources.requests.memory }}
            limits:
              cpu: {{ .Values.auth.resources.limits.cpu }}
              memory: {{ .Values.auth.resources.limits.memory }}
