apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
  labels:
    app: teastore
    run: teastore-image
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: teastore
      run: teastore-image
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-image
    spec:
      terminationGracePeriodSeconds: 0
      initContainers:
        - name: wait-for-teastore-recommender
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "ðŸ•“ Waiting for teastore-recommender to become ready..."
              until nc -z teastore-recommender 8080; do
                echo "teastore-recommender not ready yet... sleeping 5s"
                sleep 5
              done
              echo "âœ… teastore-recommender is ready!"
      containers:
        - name: teastore-image
          image: "{{ .Values.image.image }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: HOST_NAME
              value: "teastore-image"
            - name: REGISTRY_HOST
              value: "teastore-registry"
            - name: RABBITMQ_HOST
              value: "teastore-rabbitmq"
          # readinessProbe:
          #   httpGet:
          #     path: "/tools.descartes.teastore.image/rest/image/finished"
          #     port: {{ .Values.service.port }}
          #     scheme: HTTP
          #   initialDelaySeconds: 15
          #   timeoutSeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1
          #   failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.imageService.resources.requests.cpu }}
              memory: {{ .Values.imageService.resources.requests.memory }}
            limits:
              cpu: {{ .Values.imageService.resources.limits.cpu }}
              memory: {{ .Values.imageService.resources.limits.memory }}
